Resources: 
  STAFFNOW_DB:
    Type: AWS::RDS::DBInstance
Properties: 
  AllocatedStorage: "5"
  AllowMajorVersionUpgrade: False
  AutoMinorVersionUpgrade: False
  BackupRetentionPeriod: 30
  CopyTagsToSnapshot: True
  DBName: staffnow
  DBSecurityGroups: 
    - String
  DBSnapshotIdentifier: staffnow_db_snapshot
  DBSubnetGroupName: String
  DeleteAutomatedBackups: True
  DeletionProtection: False
  Engine: postgres
  Iops: 50000
  MasterUsername: postgres
  MasterUserPassword: 1rKW6eXQXlQ7
  MaxAllocatedStorage: 10
  MultiAZ: True
  Port: "5432"
  ProcessorFeatures: 
    - ProcessorFeature
  PromotionTier: Integer
  PubliclyAccessible: False
  StorageEncrypted: True
  Tags: 
    - Tag
  UseDefaultProcessorFeatures: Boolean
  VPCSecurityGroups: 
    - String
