AWSTemplateFormatVersion: 2010-09-09
Description: Add Postgres Database

Parameters:
  MasterUsername:
    Type: String 
  MasterUserPassword:
    Type: String

Resources: 
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: sg-postgres
      GroupDescription: PostgresDB traffic
      VpcId: vpc-0415c9f8f9a75cacb
      SecurityGroupEgress:
      - IpProtocol: -1
        CidrIp: 0.0.0.0/0

  DBSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    DependsOn: DBSecurityGroup
    Properties:
      GroupId: !Ref DBSecurityGroup
      IpProtocol: tcp
      FromPort: 5432
      ToPort: 5432
      SourceSecurityGroupId: !Ref DBSecurityGroup

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: subnetgroup
      DBSubnetGroupDescription: Subnet Group
      SubnetIds:
      - subnet-0cb1a6355856d6c93
      - subnet-006122649211363af

  STAFFNOWDB:
    Type: AWS::RDS::DBInstance
    Properties: 
      AllocatedStorage: 5
      AllowMajorVersionUpgrade: False
      AutoMinorVersionUpgrade: False
      BackupRetentionPeriod: 30
      CopyTagsToSnapshot: True
      DBName: staffnow
      DBInstanceClass: db.t3.micro
      DBSnapshotIdentifier: staffnow_db_snapshot
      DBSubnetGroupName: !Ref DBSubnetGroup
      DeleteAutomatedBackups: True
      DeletionProtection: False
      Engine: postgres
      Iops: 50000
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      MaxAllocatedStorage: 10
      MultiAZ: True
      Port: 5432
      PubliclyAccessible: False
      StorageEncrypted: True
      Tags: 
        - Key: Name
          Value: Staffnow_db_dev
      DeletionPolicy: Snapshot
      UpdateReplacePolicy: Snapshot
      UseDefaultProcessorFeatures: True
      VPCSecurityGroups: 
        - !Ref DBSecurityGroup
