AWSTemplateFormatVersion: 2010-09-09
Description: Add Postgres Database
Resources: 
  STAFFNOW_DB:
    Type: AWS::RDS::DBInstance
Properties: 
  AllocatedStorage: "5"
  AllowMajorVersionUpgrade: False
  AutoMinorVersionUpgrade: False
  BackupRetentionPeriod: 30
  CopyTagsToSnapshot: True
  DBName: staffnow
  DBInstanceClass: db.t3.micro
  DBSecurityGroups: 
    - String
  DBSnapshotIdentifier: staffnow_db_snapshot
  DBSubnetGroupName: String
  DeleteAutomatedBackups: True
  DeletionProtection: False
  Engine: postgres
  Iops: 50000
  MasterUsername: postgres
  MasterUserPassword: 1rKW6eXQXlQ7
  MaxAllocatedStorage: 10
  MultiAZ: True
  Port: "5432"
  PubliclyAccessible: False
  StorageEncrypted: True
  Tags: 
    - Key: Name
      Value: Staffnow_db_dev
  DeletionPolicy: Snapshot
  UpdateReplacePolicy: Snapshot
  UseDefaultProcessorFeatures: True
  VPCSecurityGroups: 
    - String
